# Application name
spring.application.name=triVial

# PostgreSQL database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/trivial_db
spring.datasource.username=danielperez
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA  / Hibernate configurations
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true